### PR TITLE
updated dart-sass to 1.25.0

### PR DESCRIPTION
**Pull request by freiit**
Fix for #118 and #120 .

### CODE REVIEW

**Comment by freiit** [comment]
@googlebot I signed it!

**Comment by AjithPG** [comment]
@use is coming soon, but it's not supported in this version of Dart Sass
I got this error while building  material design.How can i solve this

**Comment by danbst** [comment]
@kfranqueiro @asyncLiz got scss compilation error as well. Confirm, this PR fixes the issue

**Comment by asyncLiz** [comment]
It looks like you've only update package.json and not package-lock.json files. Can you run `npm install dart-sass@latest` in each sub-folder? Running the command will also update the lock file.

Updating to the latest version of Dart Sass will fix `@use` not being available.

**Comment by abhiomkar** [comment]
Superseded by #136

**Pull request closed without merging**
